[package]
name = "targeting"
version = "0.1.0"
edition = "2021"

[lib]
name = "targeting"
path = "src/lib.rs"

[[bin]]
name = "targeting"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
async-graphql = { workspace = true }
aws-credential-types = { workspace = true }
aws-sdk-s3 = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
derive_more = { workspace = true }
dotenvy = { workspace = true }
graphql_endpoints = { path = "../graphql_endpoints" }
graphql_event_broker = { path = "../graphql_event_broker" }
opa_client = { path = "../opa_client", features = ["graphql"] }
sea-orm = { workspace = true, features = ["sqlx-postgres"] }
sea-orm-migration = { workspace = true }
tokio = { workspace = true }
tokio-stream = { version = "0.1.16" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
