name: Policy

on:
  push:
  pull_request:

jobs:
  lint:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.4

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
      
      - name: Run OPA Lints
        run: opa check --strict policies/

  test:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.4

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
      
      - name: Run OPA Tests
        run: opa test policies/
